Add mpv

diff --git a/.chezmoiscripts/run_onchange_04-mpv.tmpl b/.chezmoiscripts/run_onchange_04-mpv.tmpl
--- a/.chezmoiscripts/run_onchange_04-mpv.tmpl
+++ b/.chezmoiscripts/run_onchange_04-mpv.tmpl
@@ -3,11 +3,63 @@
 
 echo -e "\n\033[1m━━━  mpv plugins  ━━━\033[0m"
 
-# local mpv_scripts="$HOME/.config/mpv/scripts"
-# mkdir -p "$mpv_scripts"
+update_script() {
+  local url="$1"
+  local dir="$HOME/.config/mpv/$2"
+  local filename=$(basename ${url})
 
-# TODO: add plugin repos here, for example:
-# clone_or_update "https://github.com/example/mpv-plugin.git" \
-#                 "$mpv_scripts/plugin-name"
-echo -e "\033[1;33m\033[1m[TODO]\033[0m  mpv plugin setup."
+  mkdir -p "$dir"
+
+  if [[ $dir == "$HOME/.config/mpv/scripts" ]]; then
+    wget --quiet "${url}" -O "${dir}/${filename}"
+    ([[ $? -eq 0 ]] && echo -e "\033[0;32m\033[1m[OK]\033[0m    Script updated: ${filename}") || echo -e "\033[1m[ERROR]\033[0m Error while updating script ${filename}" >&2
+  elif [[ $dir == $HOME/.config/mpv/script-opts ]]; then
+    if [[ ! -f "${dir}/${filename}" ]]; then
+      wget --quiet "${url}" -O "${dir}/${filename}"
+      ([[ $? -eq 0 ]] && echo -e "\033[0;32m\033[1m[OK]\033[0m    Config downloaded: ${filename}") || echo -e "\033[1m[ERROR]\033[0m Error while updating config ${filename}" >&2
+    fi
+  else
+    wget --quiet "${url}" -O "${dir}/${filename}"
+    ([[ $? -eq 0 ]] && echo -e "\033[0;32m\033[1m[OK]\033[0m    Script files downloaded into: ${dir}") || echo -e "\033[1m[ERROR]\033[0m Error while script files ${filename}" >&2
+  fi
+}
+
+update_uosc() {
+  echo -e "\033[0;36m\033[1m[INFO]\033[0m  Updating uosc"
+  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/tomasklaen/uosc/HEAD/installers/unix.sh)" >/dev/null 2>&1
+  ([[ $? -eq 0 ]] && echo -e "\033[0;32m\033[1m[OK]\033[0m    Script updated: uosc") || echo -e "\033[1m[ERROR]\033[0m Error while updating script uosc" >&2
+}
+
+update_autosubsync() {
+  # # TODO https://github.com/po5/mpv_sponsorblock or https://codeberg.org/jouni/mpv_sponsorblock_minimal
+
+  echo -e "\033[0;36m\033[1m[INFO]\033[0m  Updating autosubsync"
+
+  rm -rf $HOME/.config/mpv/scripts/autosubsync
+  git clone 'https://github.com/Ajatt-Tools/autosubsync-mpv' $HOME/.config/mpv/scripts/autosubsync >/dev/null 2>&1
+  ([[ $? -eq 0 ]] && echo -e "\033[0;32m\033[1m[OK]\033[0m    Script updated: autosubsync") || echo -e "\033[1m[ERROR]\033[0m Error while updating script autosubsync" >&2
+}
+
+update_sponsorblock() {
+  echo -e "\033[0;36m\033[1m[INFO]\033[0m  Updating sponsorblock"
+
+  rm -rf $HOME/.config/mpv/scripts/sponsorblock_shared $HOME/.config/mpv/scripts/sponsorblock.lua
+
+  local tempdir=$(mktemp -d)
+  git clone 'https://github.com/po5/mpv_sponsorblock' $tempdir >/dev/null 2>&1 && mv ${tempdir}/sponsorblock_shared ${tempdir}/sponsorblock.lua $HOME/.config/mpv/scripts/
+  ([[ $? -eq 0 ]] && echo -e "\033[0;32m\033[1m[OK]\033[0m    Script updated: sponsorblock") || echo -e "\033[1m[ERROR]\033[0m Error while updating script sponsorblock" >&2
+}
+
+scripts=({{ .mpv_plugins.urls | quoteList | join " " }})
+
+for element in "${scripts[@]}"; do
+  func=false
+  for p in "uosc" "autosubsync" "sponsorblock"; do
+    if [[ "$element" == "$p" ]]; then update_$p; func=true; fi
+  done
+  [[ "$func" == true ]] && continue
+  values=($element)
+  update_script ${values[0]} ${values[1]}
+done
+
 {{ end -}}
